# Generated by Django 4.0.2 on 2022-06-26 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FAQ', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='frequentlyaskedquestion',
            name='description',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='frequentlyaskedquestion',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
