# Generated by Django 2.2 on 2020-12-26 11:54

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mymodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text="\n            contains jsons in a specific order in the list\n            each json's key shows a warehouse id as an integer\n            each json's value shows that the cargo has either reached there or not\n            so the json values are booleans        \n            ", null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SMSLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('params_receptor', models.CharField(blank=True, max_length=32, null=True)),
                ('params_message', models.TextField(blank=True, null=True)),
                ('params_sender', models.CharField(blank=True, max_length=32, null=True)),
                ('params_template', models.CharField(blank=True, max_length=32, null=True)),
                ('params_token', models.CharField(blank=True, max_length=32, null=True)),
                ('params_type', models.CharField(blank=True, max_length=32, null=True)),
                ('validation', models.BooleanField(blank=True, null=True)),
                ('messageid', models.IntegerField(null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('status', models.IntegerField(blank=True, null=True)),
                ('statustext', models.TextField(blank=True, null=True)),
                ('sender', models.CharField(blank=True, max_length=32, null=True)),
                ('receptor', models.CharField(blank=True, max_length=32, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('cost', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
