# Generated by Django 2.2 on 2021-02-11 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0013_internalcontract_low_limit_credit'),
        ('developinglogs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditDueDateCheckerDetial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('paid', models.BooleanField(default=False)),
                ('credit_due_date', models.ForeignKey(blank=True, null=True, on_delete=models.CASCADE, to='contracts.CreditDueDate')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
