# Generated by Django 2.2 on 2021-02-11 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('developinglogs', '0002_creditduedatecheckerdetial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CreditDueDateCheckerDetial',
        ),
    ]
