# Generated by Django 2.2 on 2021-03-01 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developinglogs', '0003_delete_creditduedatecheckerdetial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smslog',
            name='statustext',
        ),
        migrations.AlterField(
            model_name='smslog',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'در صف ارسال قرار دارد'), (2, 'زمان بندی شده (ارسال در تاریخ معین)'), (4, 'ارسال شده به مخابرات'), (5, 'ارسال شده به مخابرات (همانند وضعیت 4)'), (6, 'خطا در ارسال پیام که توسط سر شماره پیش می آید و به معنی عدم رسیدن پیامک می\u200cباشد (Failed)'), (10, 'رسیده به گیرنده (Delivered)'), (11, 'نرسیده به گیرنده ، این وضعیت به دلایلی از جمله خاموش یا خارج از دسترس بودن گیرنده اتفاق می افتد (Undelivered)'), (13, 'ارسال پیام از سمت کاربر لغو شده یا در ارسال آن مشکلی پیش آمده که هزینه آن به حساب برگشت داده می\u200cشود'), (14, 'بلاک شده است، عدم تمایل گیرنده به دریافت پیامک از خطوط تبلیغاتی که هزینه آن به حساب برگشت داده می\u200cشود'), (100, 'شناسه پیامک نامعتبر است ( به این معنی که شناسه پیام در پایگاه داده کاوه نگار ثبت نشده است یا متعلق به شما نمی\u200cباشد)')], null=True),
        ),
    ]
