# Generated by Django 2.2 on 2021-04-14 03:57

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('developinglogs', '0004_auto_20210301_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymodel',
            name='answer',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text=",\n            contains jsons in a specific order in the list\n            each json's key shows a warehouse id as an integer\n            each json's value shows that the cargo has either reached there or not\n            so the json values are booleans        \n            ", null=True),
        ),
    ]
