# Generated by Django 3.2.5 on 2021-07-06 10:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('developinglogs', '0005_auto_20210414_0827'),
    ]

    operations = [
        migrations.AddField(
            model_name='smslog',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 6, 10, 17, 22, 621959, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='mymodel',
            name='answer',
            field=models.JSONField(blank=True, help_text=",\n            contains jsons in a specific order in the list\n            each json's key shows a warehouse id as an integer\n            each json's value shows that the cargo has either reached there or not\n            so the json values are booleans        \n            ", null=True),
        ),
    ]
