# Generated by Django 3.2.5 on 2021-07-06 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developinglogs', '0006_auto_20210706_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smslog',
            name='created_date',
            field=models.DateTimeField(default='django.utils.timezone.now'),
        ),
    ]
