# Generated by Django 3.2.5 on 2021-07-06 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developinglogs', '0008_alter_smslog_messageid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smslog',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
