# Generated by Django 3.2.5 on 2021-07-06 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developinglogs', '0009_alter_smslog_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smslog',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
