# Generated by Django 3.2.5 on 2021-07-18 07:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('developinglogs', '0010_alter_smslog_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='smslog',
            name='kind',
            field=models.IntegerField(blank=True, choices=[(1, 'احراز هویت مشتری - وبسایت'), (2, 'احراز هویت مشتری - اوپراتور'), (3, 'احراز هویت کاربر سازمانی'), (4, 'سفارش ثبت شد'), (5, 'استعلام قیمت تایید شد'), (6, 'پیگیری استعلام قیمت')], null=True),
        ),
        migrations.AddField(
            model_name='smslog',
            name='send_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
