# Generated by Django 3.2.5 on 2021-07-25 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developinglogs', '0011_auto_20210718_1154'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmsSend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.SmallIntegerField(blank=True, null=True)),
                ('is_send', models.BooleanField(blank=True, null=True)),
            ],
        ),
    ]
