# Generated by Django 3.2.5 on 2021-08-29 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('developinglogs', '0013_auto_20210829_1017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smslog',
            name='kind',
        ),
    ]
