# Generated by Django 3.2.5 on 2021-08-30 05:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('developinglogs', '0014_remove_smslog_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='smscategory',
            name='activeBy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='smscategory',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default='2021-12-05'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='smscategory',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
