# Generated by Django 3.2.5 on 2021-09-07 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developinglogs', '0015_auto_20210830_1014'),
    ]

    operations = [
        migrations.AddField(
            model_name='smslog',
            name='is_sending',
            field=models.BooleanField(default=True),
        ),
    ]
