# Generated by Django 3.2.5 on 2021-09-30 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developinglogs', '0016_smslog_is_sending'),
    ]

    operations = [
        migrations.AddField(
            model_name='smscategory',
            name='kind',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'واردات'), (2, 'صادرات'), (3, 'داخلی'), (4, 'اپراتور'), (5, 'ادمین'), (6, 'بازاریابی'), (7, 'متفرقه')], null=True),
        ),
    ]
