# Generated by Django 3.2.5 on 2021-10-20 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developinglogs', '0017_smscategory_kind'),
    ]

    operations = [
        migrations.CreateModel(
            name='recievedSms',
            fields=[
                ('id', models.AutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('messageid', models.BigIntegerField(
                    help_text='شناسه پیامک دریافتی که به شما کمک می کند پیامک های تکراری را دریافت نکنید', null=True)),
                ('message', models.TextField(blank=True,
                 help_text='متن پیامک دریافت شده', null=True)),
                ('sender', models.CharField(blank=True,
                 help_text='شماره فرستنده پیامک', max_length=32, null=True)),
                ('receptor', models.CharField(blank=True,
                 help_text='شماره گیرنده پیامک', max_length=32, null=True)),
                ('time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
