# Generated by Django 3.2.5 on 2021-10-20 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('developinglogs', '0018_recievedsms'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='recievedSms',
            new_name='RecievedSmss',
        ),
    ]
