# Generated by Django 3.2.5 on 2021-10-20 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('developinglogs', '0019_rename_recievedsms_recievedsmss'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RecievedSmss',
            new_name='ReceivedSms',
        ),
    ]
