# Generated by Django 3.2.5 on 2022-01-25 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developinglogs', '0021_receivedsms_sender_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receivedsms',
            name='messageid',
            field=models.BigIntegerField(blank=True, help_text='شناسه پیامک دریافتی که به شما کمک می کند پیامک های تکراری را دریافت نکنید', null=True),
        ),
    ]
