# Generated by Django 3.2.5 on 2022-02-26 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developinglogs', '0022_alter_receivedsms_messageid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receivedsms',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='receivedsms',
            name='modified',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='smscategory',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='smscategory',
            name='modified',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
