# Generated by Django 3.2.5 on 2022-02-26 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developinglogs', '0023_auto_20220226_1040'),
    ]

    operations = [
        migrations.AddField(
            model_name='mymodel',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='mymodel',
            name='modified',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
