# Generated by Django 4.0.2 on 2022-07-24 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('fname', models.CharField(blank=True, help_text='country name in persian', max_length=500, null=True)),
                ('ename', models.CharField(blank=True, help_text='country name in english', max_length=100, null=True)),
                ('code', models.CharField(blank=True, help_text='country 2 digit code', max_length=100, null=True)),
                ('code3', models.CharField(blank=True, help_text='country 3 digit code', max_length=100, null=True)),
                ('capital', models.CharField(blank=True, help_text='country capital city. not related to city. only characters', max_length=100, null=True)),
                ('postal_code_format', models.CharField(blank=True, help_text='country postal code format', max_length=100, null=True)),
                ('postal_code_regex', models.CharField(blank=True, help_text='country postal code regex', max_length=500, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
