# Generated by Django 4.0.2 on 2022-07-24 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('fname', models.CharField(blank=True, help_text='persian name of the city', max_length=100, null=True)),
                ('ename', models.CharField(blank=True, help_text='english name of the city', max_length=100, null=True)),
                ('timezone', models.CharField(blank=True, help_text='city timezone in characters and not +- from greenwich?', max_length=40, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
