# Generated by Django 4.0.2 on 2022-07-24 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='DialCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('fname', models.CharField(blank=True, help_text='persian name of the country', max_length=225, null=True)),
                ('ename', models.CharField(blank=True, help_text='standard english name of the country', max_length=225, null=True)),
                ('flag', models.CharField(blank=True, help_text='flag emoji of the country', max_length=225, null=True)),
                ('code', models.CharField(blank=True, help_text='2 digit code for the country', max_length=225, null=True)),
                ('dial_code', models.CharField(blank=True, help_text='dial code with a "+" at first and the rest of it is integer', max_length=225, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
