# Generated by Django 4.0.2 on 2022-07-26 05:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_dialcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='country',
            field=models.ForeignKey(blank=True, help_text='specifies the country that city is in it.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='city_country', to='places.country'),
        ),
    ]
