# Generated by Django 4.0.2 on 2022-07-28 04:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_city_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='country',
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('fname', models.CharField(blank=True, help_text='state name in persian', max_length=100, null=True)),
                ('ename', models.CharField(blank=True, help_text='state name in english', max_length=100, null=True)),
                ('ename_std', models.CharField(blank=True, help_text='standard form of state name in english (best practice and better than ename)', max_length=100, null=True)),
                ('country', models.ForeignKey(blank=True, help_text='specifies the country that state is in it.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='state_country', to='places.country')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='city',
            name='state',
            field=models.ForeignKey(blank=True, help_text='specifies the state that city is in it.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='places.state'),
        ),
    ]
