# Generated by Django 4.0.2 on 2022-07-31 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0005_remove_city_country_state_city_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dialcode',
            name='flag',
        ),
        migrations.AddField(
            model_name='dialcode',
            name='dial_code_backup',
            field=models.CharField(blank=True, help_text='Backup for dial code', max_length=225, null=True),
        ),
    ]
