# Generated by Django 4.0.2 on 2022-08-01 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0006_remove_dialcode_flag_dialcode_dial_code_backup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dialcode',
            name='dial_code_backup',
        ),
    ]
