# Generated by Django 4.0.2 on 2022-08-13 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0007_remove_dialcode_dial_code_backup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='code',
            field=models.CharField(blank=True, help_text='country 2 digit code', max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='state',
            name='country',
            field=models.ForeignKey(blank=True, default='IR', help_text='specifies the country that state is in it.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='state_country', to='places.country', to_field='code'),
        ),
    ]
