# Generated by Django 4.0.2 on 2022-08-13 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0008_alter_country_code_alter_state_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='country',
            field=models.ForeignKey(blank=True, help_text='specifies the country that state is in it.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='state_country', to='places.country'),
        ),
    ]
