# Generated by Django 4.0.2 on 2022-02-17 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='path',
            new_name='file_field',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='subject',
            new_name='title',
        ),
    ]
