# Generated by Django 4.0.2 on 2022-03-12 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file_field',
            field=models.FileField(blank=True, null=True, upload_to='MEDIA/'),
        ),
    ]
