# Generated by Django 4.0.2 on 2022-02-26 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='tags',
            field=models.ManyToManyField(blank=True, to='System.Tag'),
        ),
    ]
