# Generated by Django 4.0.2 on 2022-04-25 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0002_ticket_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='to_department',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
