# Generated by Django 4.0.2 on 2022-02-17 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0002_rename_path_file_file_field_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='tag',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
