# Generated by Django 4.0.2 on 2022-03-28 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0002_alter_file_file_field'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='to_operator',
            new_name='reciever',
        ),
        migrations.RenameField(
            model_name='answer',
            old_name='user',
            new_name='sender',
        ),
    ]
