# Generated by Django 4.0.2 on 2022-02-19 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0003_ticket_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='title',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
