# Generated by Django 4.0.2 on 2022-03-05 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0003_alter_ticket_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='System.answer'),
        ),
    ]
