# Generated by Django 4.0.2 on 2022-02-20 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0004_alter_ticket_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e_name', models.CharField(blank=True, max_length=30, null=True)),
                ('f_name', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='file',
            name='file_field',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='tag',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
