# Generated by Django 4.0.2 on 2022-03-06 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0004_file_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='kind',
            field=models.IntegerField(choices=[(1, 'internal organizational'), (2, 'extra organizational')], default=1),
        ),
    ]
