# Generated by Django 4.0.2 on 2022-06-19 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0004_rename_e_name_tag_ename_rename_f_name_tag_fname'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='modified',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='modified',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
