# Generated by Django 4.0.2 on 2022-06-19 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0005_category_created_category_modified_tag_created_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='ename',
        ),
        migrations.AddField(
            model_name='category',
            name='fname',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
