# Generated by Django 4.0.2 on 2022-02-20 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0005_tag_remove_file_file_field_alter_ticket_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='tag',
        ),
        migrations.AddField(
            model_name='tag',
            name='ticket',
            field=models.ManyToManyField(to='System.Ticket'),
        ),
    ]
