# Generated by Django 4.0.2 on 2022-03-28 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0005_alter_ticket_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='waybill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=30, null=True)),
                ('waybill_id', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
