# Generated by Django 4.0.2 on 2022-06-25 04:06

import System.formatChecker
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0006_rename_name_category_ename_category_fname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=System.formatChecker.ContentTypeRestrictedFileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
