# Generated by Django 4.0.2 on 2022-02-20 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0006_remove_ticket_tag_tag_ticket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='ticket',
        ),
        migrations.AddField(
            model_name='ticket',
            name='tags',
            field=models.ManyToManyField(to='System.Tag'),
        ),
    ]
