# Generated by Django 4.0.2 on 2022-03-30 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0006_waybill'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='deleted',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='deleted',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
