# Generated by Django 4.0.2 on 2022-03-07 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0007_ticket_category_ticket_sub_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='to_department',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='answer',
            name='to_operator',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
