# Generated by Django 4.0.2 on 2022-04-17 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0007_answer_deleted_ticket_deleted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='file_field',
            new_name='file',
        ),
    ]
