# Generated by Django 4.0.2 on 2022-02-20 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0007_remove_tag_ticket_ticket_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='System.Tag'),
        ),
    ]
