# Generated by Django 4.0.2 on 2022-02-20 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0008_alter_ticket_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='is_answered',
        ),
        migrations.AddField(
            model_name='ticket',
            name='status',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
