# Generated by Django 4.0.2 on 2022-06-25 06:17

from django.db import migrations, models
import user.models.user


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0008_alter_file_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='reciever',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name=user.models.user.User),
        ),
    ]
