# Generated by Django 4.0.2 on 2022-03-07 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0008_answer_to_department_answer_to_operator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='is_suspended',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.IntegerField(choices=[(0, 'baste'), (1, 'jari'), (2, 'baz'), (3, 'is_suspended')], default=2),
        ),
    ]
