# Generated by Django 4.0.2 on 2022-06-25 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0009_alter_answer_reciever'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='reciever',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='MEDIA/'),
        ),
    ]
