# Generated by Django 4.0.2 on 2022-03-09 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0009_remove_ticket_is_suspended_alter_ticket_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Department',
        ),
    ]
