# Generated by Django 4.0.2 on 2022-06-26 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0010_alter_answer_reciever_alter_file_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='reciever',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='to_department',
        ),
    ]
