# Generated by Django 4.0.2 on 2022-02-21 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0010_remove_file_user_file_file_field_alter_ticket_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='file_field',
            new_name='fileField',
        ),
    ]
