# Generated by Django 4.0.2 on 2022-03-09 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0011_alter_ticket_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='department',
        ),
    ]
