# Generated by Django 4.0.2 on 2022-02-21 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0011_rename_file_field_file_filefield'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='fileField',
            new_name='file_field',
        ),
    ]
