# Generated by Django 4.0.2 on 2022-06-26 05:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0003_rename_e_name_department_ename_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('System', '0011_remove_answer_reciever_remove_answer_to_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='reciever',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recivers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='answer',
            name='to_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='department.department'),
        ),
    ]
