# Generated by Django 4.0.2 on 2022-06-29 05:11

import System.formatChecker
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0012_answer_reciever_answer_to_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('url', models.CharField(blank=True, max_length=250, null=True)),
                ('file', System.formatChecker.ContentTypeRestrictedFileField(blank=True, null=True, upload_to='MEDIA/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='file',
            name='file',
            field=System.formatChecker.ContentTypeRestrictedFileField(blank=True, null=True, upload_to='MEDIA/'),
        ),
        migrations.AlterField(
            model_name='file',
            name='name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
