# Generated by Django 4.0.2 on 2022-02-21 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0012_rename_filefield_file_file_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='is_answered',
            field=models.BooleanField(default=0),
        ),
    ]
