# Generated by Django 4.0.2 on 2022-02-22 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0013_ticket_is_answered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file_field',
            field=models.FileField(blank=True, null=True, upload_to='media/'),
        ),
    ]
