# Generated by Django 4.0.2 on 2022-06-29 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0013_url_alter_file_file_alter_file_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='System.ticket'),
        ),
    ]
