# Generated by Django 4.0.2 on 2022-02-22 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0014_alter_file_file_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='priority',
            field=models.IntegerField(choices=[(0, 'LOW'), (1, 'MIDDLE'), (2, 'HIGH')], default=0),
        ),
        migrations.AddField(
            model_name='ticket',
            name='ticket_Kind',
            field=models.IntegerField(choices=[(0, 'DARUN SAZMANI'), (1, 'BIRUN SAZMANI')], default=1),
        ),
    ]
