# Generated by Django 4.0.2 on 2022-07-07 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0015_url_answer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='url',
            old_name='file',
            new_name='files',
        ),
    ]
