# Generated by Django 4.0.2 on 2022-02-22 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0016_ticket_created_by_alter_ticket_operator_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='ticket_Kind',
            new_name='Kind',
        ),
    ]
