# Generated by Django 4.0.2 on 2022-07-07 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0016_rename_file_url_files'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='file',
            new_name='files',
        ),
        migrations.RenameField(
            model_name='url',
            old_name='files',
            new_name='file',
        ),
    ]
