# Generated by Django 4.0.2 on 2022-07-09 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0017_rename_file_file_files_rename_files_url_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='files',
            new_name='file',
        ),
    ]
