# Generated by Django 4.0.2 on 2022-02-22 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0017_rename_ticket_kind_ticket_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='Kind',
            field=models.IntegerField(blank=True, choices=[(0, 'DARUN SAZMANI'), (1, 'BIRUN SAZMANI')], default=1, null=True),
        ),
    ]
