# Generated by Django 4.0.2 on 2022-07-11 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0018_rename_files_file_file'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Url',
        ),
    ]
