# Generated by Django 4.0.2 on 2022-02-22 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0018_alter_ticket_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='Kind',
            field=models.IntegerField(blank=True, choices=[(1, 'DARUN SAZMANI'), (2, 'BIRUN SAZMANI')], default=1, null=True),
        ),
    ]
