# Generated by Django 4.0.2 on 2022-07-11 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0019_delete_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='url',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
