# Generated by Django 4.0.2 on 2022-02-22 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0019_alter_ticket_kind'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='Kind',
        ),
    ]
