# Generated by Django 4.0.2 on 2022-02-22 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0021_ticket_kind'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='Kind',
            new_name='kind',
        ),
    ]
