# Generated by Django 4.0.2 on 2022-07-23 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0022_alter_reviews_ticket_alter_reviews_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviews',
            name='ticket',
        ),
    ]
