# Generated by Django 4.0.2 on 2022-07-23 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0023_remove_reviews_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='reviews',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='System.reviews'),
        ),
    ]
