# Generated by Django 4.0.2 on 2022-07-24 04:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0025_rename_reviews_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='reviews',
        ),
        migrations.AddField(
            model_name='review',
            name='ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='System.ticket'),
        ),
    ]
