# Generated by Django 4.0.2 on 2022-07-24 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0026_remove_ticket_reviews_review_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='reaction',
            field=models.IntegerField(choices=[(0, 'Thumbs Down'), (1, 'Thinking Face'), (2, 'Red Heart'), (3, 'Thmbs Up ')], default=3),
        ),
    ]
