# Generated by Django 4.0.2 on 2022-02-23 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0026_alter_ticket_user_alter_userprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='kind',
            field=models.IntegerField(choices=[(1, 'DARUN SAZMANI'), (2, 'BIRUN SAZMANI')], default=1),
        ),
    ]
