# Generated by Django 4.0.2 on 2022-07-24 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0027_answer_reaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='comment',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
