# Generated by Django 4.0.2 on 2022-07-25 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0029_alter_answer_reaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='reaction',
            field=models.IntegerField(choices=[(0, 'Thumbs Down'), (1, 'Thmbs Up '), (2, 'Thinking Face'), (3, 'Red Heart')], default=3, null=True),
        ),
    ]
