# Generated by Django 4.0.2 on 2022-02-24 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0031_alter_userprofile_managers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='username',
        ),
    ]
