# Generated by Django 4.0.2 on 2022-07-30 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0035_review_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='signiture',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
