# Generated by Django 4.0.2 on 2022-07-30 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0036_answer_signiture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='signiture',
        ),
    ]
