# Generated by Django 4.0.2 on 2022-07-30 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0037_remove_answer_signiture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='reaction',
            field=models.IntegerField(blank=True, choices=[(0, 'Thumbs Down'), (1, 'Thmbs Up ')], null=True),
        ),
    ]
