# Generated by Django 4.0.2 on 2022-08-09 08:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('System', '0038_alter_answer_reaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='opertor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='operator_Review', to=settings.AUTH_USER_MODEL),
        ),
    ]
