# Generated by Django 4.0.2 on 2022-08-09 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0040_ticket_rated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='opertor',
            new_name='operator',
        ),
    ]
