# Generated by Django 4.0.2 on 2022-08-10 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0041_rename_opertor_review_operator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='rated',
        ),
    ]
