# Generated by Django 4.0.2 on 2022-08-10 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0042_remove_ticket_rated'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='rated',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
