# Generated by Django 4.0.2 on 2022-08-14 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0043_review_rated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='rated',
            new_name='rated_one',
        ),
        migrations.AddField(
            model_name='review',
            name='rated_two',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
