# Generated by Django 4.0.2 on 2022-08-14 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0044_rename_rated_review_rated_one_review_rated_two'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='rated_one',
            new_name='rated',
        ),
        migrations.RemoveField(
            model_name='review',
            name='rated_two',
        ),
    ]
