# Generated by Django 4.0.2 on 2022-08-14 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0046_rename_rated_review_rated_one_review_rated_two'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='rated_one',
            new_name='rated_operator',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='rated_two',
            new_name='rated_user',
        ),
    ]
