# Generated by Django 4.0.2 on 2022-08-16 09:10

import System.formatChecker
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0048_file_file_format'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=System.formatChecker.ContentTypeRestrictedFileField(blank=True, default=[], null=True, upload_to='MEDIA/'),
        ),
    ]
