# Generated by Django 4.0.2 on 2022-09-06 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0050_alter_file_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='rated_operator',
        ),
        migrations.RemoveField(
            model_name='review',
            name='rated_user',
        ),
        migrations.AddField(
            model_name='ticket',
            name='rated_operator',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='rated_user',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
