# Generated by Django 4.0.2 on 2022-03-10 05:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='User_log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=100)),
                ('browser', models.CharField(blank=True, max_length=300, null=True)),
                ('os', models.CharField(blank=True, max_length=300, null=True)),
                ('device', models.CharField(blank=True, max_length=300, null=True)),
                ('for_admin', models.CharField(blank=True, max_length=300, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('log_kind', models.SmallIntegerField(choices=[(0, 'ورود کاربر'), (1, 'رمز اشتباه'), (2, 'خروج کاربر'), (3, 'توکن اشتباه')], default=0, help_text='نوع لاگ')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
