# Generated by Django 3.2.5 on 2021-09-08 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0003_user_log_log_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_log',
            name='browser',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='user_log',
            name='device',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='user_log',
            name='os',
            field=models.CharField(max_length=300),
        ),
    ]
