# Generated by Django 3.2.5 on 2021-09-08 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0005_alter_user_log_log_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_log',
            name='browser',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='user_log',
            name='for_admin',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='user_log',
            name='log_kind',
            field=models.SmallIntegerField(choices=[(0, 'ورود کاربر'), (1, 'رمز اشتباه'), (2, 'خروج کاربر'), (3, 'توکن اشتباه'), (4, 'خروچ')], default=0, help_text='نوع لاگ'),
        ),
        migrations.AlterField(
            model_name='user_log',
            name='os',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
