# Generated by Django 4.0.2 on 2022-03-09 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0007_alter_user_log_log_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_log',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
