# Generated by Django 4.0.2 on 2022-03-09 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0008_alter_user_log_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_log',
            name='user',
        ),
    ]
