# Generated by Django 4.0.2 on 2022-03-17 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accesslevel', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='common_access_level',
            field=models.ForeignKey(blank=True, help_text='سطح دسترسی متداولی که کاربر به آن دسترسی دارد', null=True, on_delete=django.db.models.deletion.SET_NULL, to='accesslevel.commonaccesslevel'),
        ),
    ]
