# Generated by Django 4.0.2 on 2022-07-24 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_dialcode'),
        ('user', '0003_user_common_access_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.ForeignKey(blank=True, help_text='شهر آدرس', null=True, on_delete=django.db.models.deletion.SET_NULL, to='places.city'),
        ),
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.ForeignKey(blank=True, help_text='کشور آدرس', null=True, on_delete=django.db.models.deletion.SET_NULL, to='places.country'),
        ),
    ]
