# Generated by Django 4.0.2 on 2022-02-27 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_userprofile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.SmallIntegerField(choices=[(0, 'modir amel'), (1, 'modir mali')], default=2),
        ),
    ]
