# Generated by Django 4.0.2 on 2022-07-25 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(help_text='ایمیل', max_length=254, null=True),
        ),
    ]
