# Generated by Django 4.0.2 on 2022-07-30 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='signiture',
            field=models.CharField(blank=True, help_text='امضا', max_length=100, null=True),
        ),
    ]
