# Generated by Django 4.0.2 on 2022-07-31 05:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0005_remove_city_country_state_city_state'),
        ('user', '0008_user_signiture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='city',
        ),
        migrations.AddField(
            model_name='user',
            name='state',
            field=models.ForeignKey(blank=True, help_text='استان آدرس', null=True, on_delete=django.db.models.deletion.SET_NULL, to='places.state'),
        ),
    ]
