# Generated by Django 4.0.2 on 2022-07-31 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0006_remove_dialcode_flag_dialcode_dial_code_backup'),
        ('user', '0009_remove_user_city_user_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='country',
            field=models.ForeignKey(blank=True, help_text='کشور محل سکونت', null=True, on_delete=django.db.models.deletion.SET_NULL, to='places.country'),
        ),
        migrations.AlterField(
            model_name='user',
            name='state',
            field=models.ForeignKey(blank=True, help_text='استان محل سکونت', null=True, on_delete=django.db.models.deletion.SET_NULL, to='places.state'),
        ),
    ]
