# Generated by Django 4.0.2 on 2022-07-31 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0006_remove_dialcode_flag_dialcode_dial_code_backup'),
        ('user', '0010_alter_user_country_alter_user_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dial_code_backup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='places.dialcode'),
        ),
    ]
