# Generated by Django 4.0.2 on 2022-08-01 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_user_dial_code_backup'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='dial_code_backup',
            new_name='dial_code',
        ),
    ]
