# Generated by Django 4.0.2 on 2022-08-09 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_rename_dial_code_backup_user_dial_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='rated',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
