# Generated by Django 4.0.2 on 2022-08-10 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_user_rated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='rated',
        ),
    ]
