# Generated by Django 4.0.2 on 2022-08-16 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0009_alter_state_country'),
        ('user', '0014_remove_user_rated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='country',
            field=models.ForeignKey(blank=True, default='Iran', help_text='کشور محل سکونت', null=True, on_delete=django.db.models.deletion.SET_NULL, to='places.country'),
        ),
    ]
