# Generated by Django 4.0.2 on 2022-08-16 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0009_alter_state_country'),
        ('user', '0016_alter_user_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='state',
            field=models.ForeignKey(blank=True, default=19395, help_text='استان محل سکونت', null=True, on_delete=django.db.models.deletion.SET_NULL, to='places.state'),
        ),
    ]
