# Generated by Django 4.0.2 on 2022-09-18 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_historicaluser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaluser',
            name='role',
            field=models.SmallIntegerField(choices=[(0, 'کاربر عادی'), (1, 'کاربر داشبورد سازمانی'), (2, 'تحصیل\u200cدار'), (3, 'ادمین')], default=0, help_text='handling the user kind, role'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.SmallIntegerField(choices=[(0, 'کاربر عادی'), (1, 'کاربر داشبورد سازمانی'), (2, 'تحصیل\u200cدار'), (3, 'ادمین')], default=0, help_text='handling the user kind, role'),
        ),
    ]
