# Generated by Django 4.0.2 on 2022-09-20 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_alter_historicaluser_role_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluser',
            name='confirmation',
            field=models.SmallIntegerField(choices=[(0, 'not valid'), (1, 'valid'), (2, 'signed up')], default=0, help_text='validation status for signup'),
        ),
        migrations.AddField(
            model_name='user',
            name='confirmation',
            field=models.SmallIntegerField(choices=[(0, 'not valid'), (1, 'valid'), (2, 'signed up')], default=0, help_text='validation status for signup'),
        ),
    ]
