# Generated by Django 4.0.2 on 2022-09-20 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0020_historicaluser_confirmation_user_confirmation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaluser',
            name='email',
            field=models.EmailField(blank=True, help_text='ایمیل', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, help_text='ایمیل', max_length=254, null=True),
        ),
    ]
