# Generated by Django 4.0.2 on 2022-09-24 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0021_alter_historicaluser_email_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaluser',
            name='role',
            field=models.SmallIntegerField(choices=[(0, 'کاربر عادی'), (1, 'کاربر داشبورد سازمانی'), (2, 'تحصیل\u200cدار'), (3, 'ادمین'), (4, 'ادمین دپارتمان')], default=0, help_text='handling the user kind, role'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.SmallIntegerField(choices=[(0, 'کاربر عادی'), (1, 'کاربر داشبورد سازمانی'), (2, 'تحصیل\u200cدار'), (3, 'ادمین'), (4, 'ادمین دپارتمان')], default=0, help_text='handling the user kind, role'),
        ),
    ]
