# Generated by Django 4.0.2 on 2022-10-02 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0022_alter_historicaluser_role_alter_user_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicaluser',
            old_name='created_time',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='created_time',
            new_name='created',
        ),
    ]
