# Generated by Django 4.0.2 on 2022-10-25 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0024_alter_historicaluser_birthday_alter_user_birthday'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluser',
            name='with_email',
            field=models.BooleanField(default=False, help_text='ایا ایمیل با اعتبارسنجی شود یا خیر'),
        ),
        migrations.AddField(
            model_name='user',
            name='with_email',
            field=models.BooleanField(default=False, help_text='ایا ایمیل با اعتبارسنجی شود یا خیر'),
        ),
    ]
