# Generated by Django 2.2 on 2021-01-02 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accesslevel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccesslevelgroup',
            name='access_level_group',
        ),
        migrations.RemoveField(
            model_name='useraccesslevelgroup',
            name='granted_by',
        ),
        migrations.RemoveField(
            model_name='useraccesslevelgroup',
            name='user',
        ),
        migrations.RemoveField(
            model_name='useraccesslevelsubject',
            name='access_level_subject',
        ),
        migrations.RemoveField(
            model_name='useraccesslevelsubject',
            name='granted_by',
        ),
        migrations.RemoveField(
            model_name='useraccesslevelsubject',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserAccessLevelAction',
        ),
        migrations.DeleteModel(
            name='UserAccessLevelGroup',
        ),
        migrations.DeleteModel(
            name='UserAccessLevelSubject',
        ),
    ]
