# Generated by Django 4.0.2 on 2022-04-20 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0001_initial'),
        ('accesslevel', '0002_accesslevelrequest_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesslevelrequest',
            name='department',
            field=models.ForeignKey(blank=True, help_text='دفتری که برای دسترسی درخواست شده', null=True, on_delete=django.db.models.deletion.SET_NULL, to='department.department'),
        ),
    ]
