# Generated by Django 2.2 on 2021-01-03 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accesslevel', '0002_auto_20210102_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commonaccesslevel',
            name='actions',
            field=models.ManyToManyField(blank=True, null=True, to='accesslevel.AccessLevelAction'),
        ),
    ]
