# Generated by Django 4.0.2 on 2022-04-20 08:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accesslevel', '0003_accesslevelrequest_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesslevelrequest',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='درخواست توسط چه کسی ثبت شده', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_level_request_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='accesslevelrequest',
            name='granted_by',
            field=models.ForeignKey(blank=True, help_text='درخواست توسط چه کسی بررسی شده', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_level_request_granted_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
