# Generated by Django 2.2 on 2021-01-03 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accesslevel', '0003_auto_20210103_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commonaccesslevel',
            name='actions',
            field=models.ManyToManyField(blank=True, to='accesslevel.AccessLevelAction'),
        ),
    ]
