# Generated by Django 2.2 on 2021-02-21 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('offices', '0003_auto_20210106_1439'),
        ('accesslevel', '0004_auto_20210103_0931'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accesslevelrequest',
            name='offices',
        ),
        migrations.AddField(
            model_name='accesslevelrequest',
            name='office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='offices.Office'),
        ),
    ]
