# Generated by Django 4.0.2 on 2022-04-20 08:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accesslevel', '0004_accesslevelrequest_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrowcountaccess',
            name='user',
            field=models.ForeignKey(blank=True, help_text='if we want this limit for spedific user', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
