# Generated by Django 4.0.2 on 2022-06-11 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accesslevel', '0005_userrowcountaccess_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commonaccesslevel',
            old_name='name',
            new_name='fname',
        ),
        migrations.RenameField(
            model_name='commonaccesslevelgroup',
            old_name='name',
            new_name='fname',
        ),
    ]
