# Generated by Django 2.2 on 2021-04-14 03:57

import accesslevel.models.access_level_models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import extra_scripts.validate_image


class Migration(migrations.Migration):

    dependencies = [
        ('accesslevel', '0005_auto_20210221_1611'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accesslevelrequest',
            name='code',
        ),
        migrations.AlterField(
            model_name='accesslevelaction',
            name='access_level_group',
            field=models.ForeignKey(blank=True, help_text='این اکشن مربوط به کدام منو است', null=True, on_delete=django.db.models.deletion.SET_NULL, to='accesslevel.AccessLevelGroup'),
        ),
        migrations.AlterField(
            model_name='accesslevelaction',
            name='description',
            field=models.TextField(blank=True, help_text='توضیحات', null=True),
        ),
        migrations.AlterField(
            model_name='accesslevelaction',
            name='display_name',
            field=models.CharField(blank=True, help_text='اسم فارسی اکشن', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='accesslevelaction',
            name='name',
            field=models.CharField(blank=True, help_text='اسم انگلیسی اکشن', max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='accesslevelgroup',
            name='access_level_subject',
            field=models.ForeignKey(blank=True, help_text='موضوعی که منو در آن وجود دارد', null=True, on_delete=django.db.models.deletion.SET_NULL, to='accesslevel.AccessLevelSubject'),
        ),
        migrations.AlterField(
            model_name='accesslevelgroup',
            name='description',
            field=models.TextField(blank=True, help_text='توضیحات درباره منو', null=True),
        ),
        migrations.AlterField(
            model_name='accesslevelgroup',
            name='display_name',
            field=models.CharField(blank=True, help_text='اسم منو جهت نمایش', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='accesslevelgroup',
            name='name',
            field=models.CharField(blank=True, help_text='اسم منو که به عنوان url استفاده می\u200cشه', max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='accesslevelrequest',
            name='common_access_level',
            field=models.ForeignKey(blank=True, help_text='سطح دسترسی متداولی که درخواست شده', null=True, on_delete=django.db.models.deletion.SET_NULL, to='accesslevel.CommonAccessLevel'),
        ),
        migrations.AlterField(
            model_name='accesslevelrequest',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='درخواست توسط چه کسی ثبت شده', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_level_request_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='accesslevelrequest',
            name='granted',
            field=models.BooleanField(blank=True, help_text='آیا درخواست سطح دسترسی قبول شده یا رد شده.', null=True),
        ),
        migrations.AlterField(
            model_name='accesslevelrequest',
            name='granted_by',
            field=models.ForeignKey(blank=True, help_text='درخواست توسط چه کسی بررسی شده', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_level_request_granted_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='accesslevelrequest',
            name='negative',
            field=models.BooleanField(default=False, help_text='اگر ترو باشد یعنی درخواست سلب دسترسی و اگر فالس باشد یعنی درخواست اخذ دسترسی است'),
        ),
        migrations.AlterField(
            model_name='accesslevelrequest',
            name='not_granted_desc',
            field=models.TextField(blank=True, help_text='اگر درخواست رد شده چه توضیحاتی داشته', null=True),
        ),
        migrations.AlterField(
            model_name='accesslevelrequest',
            name='office',
            field=models.ForeignKey(blank=True, help_text='دفتری که برای دسترسی درخواست شده', null=True, on_delete=django.db.models.deletion.SET_NULL, to='offices.Office'),
        ),
        migrations.AlterField(
            model_name='accesslevelrequest',
            name='user',
            field=models.ForeignKey(blank=True, help_text='دسترسی برای چه کاربری درخواست شده؟', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_level_request_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='accesslevelsubject',
            name='description',
            field=models.TextField(blank=True, help_text='توضیحات راجع به این موضوع', null=True),
        ),
        migrations.AlterField(
            model_name='accesslevelsubject',
            name='display_name',
            field=models.CharField(blank=True, help_text='اسمی که نمایش داده میشه', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='accesslevelsubject',
            name='hovered_icon',
            field=models.ImageField(blank=True, help_text='آیکن هاور شده موضوع', null=True, upload_to=accesslevel.models.access_level_models.access_level_subject_icon_hovered_path, validators=[extra_scripts.validate_image.validate_image]),
        ),
        migrations.AlterField(
            model_name='accesslevelsubject',
            name='icon',
            field=models.ImageField(blank=True, help_text='آیکن هاور نشده', null=True, upload_to=accesslevel.models.access_level_models.access_level_subject_icon_path, validators=[extra_scripts.validate_image.validate_image]),
        ),
        migrations.AlterField(
            model_name='accesslevelsubject',
            name='importance',
            field=models.IntegerField(blank=True, help_text='میزان اهمیت موضوع. برای sort کردن موضوعات در ساید بار', null=True),
        ),
        migrations.AlterField(
            model_name='accesslevelsubject',
            name='name',
            field=models.CharField(blank=True, help_text='نام موضوع', max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='commonaccesslevel',
            name='actions',
            field=models.ManyToManyField(blank=True, help_text='اکشن\u200cهایی که این کاربر متداول دارد', to='accesslevel.AccessLevelAction'),
        ),
        migrations.AlterField(
            model_name='commonaccesslevel',
            name='common_access_level_group',
            field=models.ForeignKey(blank=True, help_text='این کاربر متداول به کدام دسته متعلق است؟', null=True, on_delete=django.db.models.deletion.SET_NULL, to='accesslevel.CommonAccessLevelGroup'),
        ),
        migrations.AlterField(
            model_name='commonaccesslevel',
            name='description',
            field=models.TextField(blank=True, help_text='توضیحات بیشتر راجع به این دسترسی متداول', null=True),
        ),
        migrations.AlterField(
            model_name='commonaccesslevel',
            name='ename',
            field=models.CharField(blank=True, help_text='اسم انگلیسی دسترسی متداول', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='commonaccesslevel',
            name='groups',
            field=models.ManyToManyField(help_text='گروه\u200cها (منو) که این کاربر متداول به آن\u200cها دسترسی دارد', to='accesslevel.AccessLevelGroup'),
        ),
        migrations.AlterField(
            model_name='commonaccesslevel',
            name='name',
            field=models.CharField(blank=True, help_text='اسم دسترسی متداول (مثلا کاربر مالی ارشد)', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='commonaccesslevel',
            name='subjects',
            field=models.ManyToManyField(help_text='موضوعاتی که این کاربر متداول به آنها دسترسی دارد', to='accesslevel.AccessLevelSubject'),
        ),
    ]
