# Generated by Django 2.2 on 2021-04-14 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accesslevel', '0006_auto_20210414_0827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commonaccesslevelgroup',
            name='ename',
            field=models.CharField(blank=True, help_text='نام انگلیسی دسته', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='commonaccesslevelgroup',
            name='name',
            field=models.CharField(blank=True, help_text='نام دسته', max_length=200, null=True),
        ),
    ]
