# Generated by Django 4.0.2 on 2022-06-11 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accesslevel', '0006_rename_name_commonaccesslevel_fname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commonaccesslevel',
            old_name='fname',
            new_name='name',
        ),
    ]
