# Generated by Django 2.2 on 2021-05-12 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accesslevel', '0007_auto_20210414_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesslevelgroup',
            name='index',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
