# Generated by Django 4.0.2 on 2022-06-11 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accesslevel', '0007_rename_fname_commonaccesslevel_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commonaccesslevel',
            old_name='name',
            new_name='fname',
        ),
    ]
