# Generated by Django 2.2 on 2021-05-12 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accesslevel', '0008_accesslevelgroup_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesslevelgroup',
            name='index',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
