# Generated by Django 2.2 on 2021-06-08 05:16

import accesslevel.models.access_level_models
from django.db import migrations, models
import extra_scripts.validate_image


class Migration(migrations.Migration):

    dependencies = [
        ('accesslevel', '0009_auto_20210512_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesslevelsubject',
            name='large_hovered_icon',
            field=models.ImageField(blank=True, help_text='آیکن بزرگ هاور شده موضوع', null=True, upload_to=accesslevel.models.access_level_models.access_level_subject_large_icon_hovered_path, validators=[extra_scripts.validate_image.validate_image]),
        ),
        migrations.AddField(
            model_name='accesslevelsubject',
            name='large_icon',
            field=models.ImageField(blank=True, help_text='آیکن بزرگ هاور نشده موضوع', null=True, upload_to=accesslevel.models.access_level_models.access_level_subject_large_icon_path, validators=[extra_scripts.validate_image.validate_image]),
        ),
    ]
