# Generated by Django 2.2 on 2021-06-09 06:20

import accesslevel.models.access_level_models
import django.core.validators
from django.db import migrations, models
import extra_scripts.validate_image


class Migration(migrations.Migration):

    dependencies = [
        ('accesslevel', '0011_auto_20210609_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesslevelsubject',
            name='hovered_icon',
            field=models.FileField(blank=True, help_text='آیکن هاور شده موضوع', null=True, upload_to=accesslevel.models.access_level_models.access_level_subject_icon_hovered_path, validators=[extra_scripts.validate_image.validate_image, django.core.validators.FileExtensionValidator(['png', 'jpg', 'svg', 'jpeg'])]),
        ),
        migrations.AlterField(
            model_name='accesslevelsubject',
            name='icon',
            field=models.FileField(blank=True, help_text='آیکن هاور نشده', null=True, upload_to=accesslevel.models.access_level_models.access_level_subject_icon_path, validators=[extra_scripts.validate_image.validate_image, django.core.validators.FileExtensionValidator(['png', 'jpg', 'svg', 'jpeg'])]),
        ),
        migrations.AlterField(
            model_name='accesslevelsubject',
            name='large_hovered_icon',
            field=models.FileField(blank=True, help_text='آیکن بزرگ هاور شده موضوع', null=True, upload_to=accesslevel.models.access_level_models.access_level_subject_large_icon_hovered_path, validators=[extra_scripts.validate_image.validate_image, django.core.validators.FileExtensionValidator(['png', 'jpg', 'svg', 'jpeg'])]),
        ),
        migrations.AlterField(
            model_name='accesslevelsubject',
            name='large_icon',
            field=models.FileField(blank=True, help_text='آیکن بزرگ هاور نشده موضوع', null=True, upload_to=accesslevel.models.access_level_models.access_level_subject_large_icon_path, validators=[extra_scripts.validate_image.validate_image, django.core.validators.FileExtensionValidator(['png', 'jpg', 'svg', 'jpeg'])]),
        ),
    ]
