# Generated by Django 2.2 on 2021-06-09 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accesslevel', '0012_auto_20210609_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesslevelsubject',
            name='large_icon',
            field=models.TextField(blank=True, help_text='آیکن بزرگ هاور نشده موضوع', null=True),
        ),
    ]
