# Generated by Django 3.2.5 on 2021-07-14 11:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accesslevel', '0014_auto_20210615_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesslevelaction',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 14, 11, 44, 59, 953524, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='accesslevelgroup',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 14, 11, 44, 59, 953524, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='accesslevelrequest',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 14, 11, 44, 59, 953524, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='accesslevelsubject',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 14, 11, 44, 59, 953524, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='commonaccesslevel',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 14, 11, 44, 59, 953524, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='commonaccesslevelgroup',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 14, 11, 44, 59, 953524, tzinfo=utc)),
        ),
    ]
