# Generated by Django 3.2.5 on 2021-07-14 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accesslevel', '0015_auto_20210714_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesslevelaction',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='accesslevelgroup',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='accesslevelrequest',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='accesslevelsubject',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='commonaccesslevel',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='commonaccesslevelgroup',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
