# Generated by Django 3.2.5 on 2021-08-01 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accesslevel', '0018_auto_20210715_0917'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accesslevelsubject',
            options={'ordering': ('index',)},
        ),
        migrations.AddField(
            model_name='accesslevelsubject',
            name='index',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
