# Generated by Django 3.2.5 on 2021-08-26 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accesslevel', '0019_auto_20210801_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesslevelgroup',
            name='hide',
            field=models.BooleanField(default=False, help_text='جهت عدم نمایش باید مقدار true شود'),
        ),
    ]
