# Generated by Django 3.2.5 on 2022-02-22 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accesslevel', '0021_userrowcountaccess'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesslevelsubject',
            name='display_name_eng',
            field=models.CharField(blank=True, help_text='english name for show', max_length=200, null=True),
        ),
    ]
