# Generated by Django 3.2.5 on 2022-02-22 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accesslevel', '0022_accesslevelsubject_display_name_eng'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesslevelgroup',
            name='display_name_eng',
            field=models.CharField(blank=True, help_text='name to show , in english', max_length=200, null=True),
        ),
    ]
