# Generated by Django 4.0.2 on 2022-03-30 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='deleted',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
