# Generated by Django 4.0.2 on 2022-06-11 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0002_rename_name_department_e_name_department_f_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='e_name',
            new_name='ename',
        ),
        migrations.RenameField(
            model_name='department',
            old_name='f_name',
            new_name='fname',
        ),
    ]
