# Generated by Django 4.0.2 on 2022-07-11 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0003_rename_e_name_department_ename_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='created_date',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='department',
            old_name='modified_date',
            new_name='modified',
        ),
    ]
