# Generated by Django 4.0.2 on 2022-09-20 08:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('department', '0004_rename_created_date_department_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='admin',
            field=models.ForeignKey(blank=True, help_text='admin of the department', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='department_admin', to=settings.AUTH_USER_MODEL),
        ),
    ]
